sudo: required

language: java

services:
  - docker

before_install:
  - docker pull maven
  - docker ps -a

install:
  - curl http://download.geonames.org/export/dump/allCountries.zip -o allCountries.zip
  - unzip allCountries.zip

script:
  - docker run -it --name clavin-test -v "$PWD":/usr/src/clavin -w /usr/src/clavin maven mvn install -DskipTests=true -Dgpg.skip=true
