sudo: required

language: java

services:
  - docker

before_install:
  - docker pull maven
  - docker images

install:
  - curl http://download.geonames.org/export/dump/allCountries.zip -o allCountries.zip
  - unzip allCountries.zip

script:
  - docker run -it --name clavin-test -v "$PWD":/usr/src/clavin -w /usr/src/clavin maven /bin/bash -c 'mvn install -DskipTests=true -Dgpg.skip=true; MAVEN_OPTS="-Xmx4g" mvn exec:java -Dexec.mainClass="com.bericotech.clavin.index.IndexDirectoryBuilder"; mvn package'
