sudo: required

language: java

services:
  - docker

before_install:
  - docker pull maven

script: 
  - travis_wait ./script/ci/run_build.sh

install:
  - docker run -it -v "$PWD":/usr/src/clavin -w /usr/src/clavin maven mvn install -DskipTests=true -Dgpg.skip=true
